name: Deploy

on:
  push:
    branches:
      - prod
  schedule:
    - cron: "33 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: prod
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
          architecture: x64
      - name: setup
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}