name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
          architecture: x64
      
      - name: setup
        run: |
          pip install pipenv
          pipenv sync --dev --pre

      - name: isort
        run: isort . --check
      - name: black
        run: black . --check
